### ISSUE TITLE
HTTP Authentication: only on services, not on requests to get metadata 

### ISSUE THREAD

**Issue by thijsbrentjens** [Geonovum/etf-test-projects-inspire#48]
Reported from E.L.F. on WFS tests: when using HTTP authentication, the credentials (intended for a service) are also used when getting metadata records. This may go wrong on some CSW implementations that also support authentication on metadata (like GeoNetwork) .

Proposal: only use credentials on the service requests, not on any metadata test.

Two approaches possible:
1) change the method updateCredentials in the Groovy script de.interactive_instruments.xtf.Util. We should have some kind of filter that the request is NOT part of the service, but to a metadata document (a nasty one when doing Atom tests: determine if the request is for metadata or for a service feed)
2) override/remove any Authorization header in the metadata get requests. This may have disadvantages if the metadata is also behind some authentication mechanism, but I think this is more rare

I prefer the second approach.

**Comment by cportele** [comment]
I agree

**Comment by thijsbrentjens** [comment]
that's fast :)

**Comment by thijsbrentjens** [comment]
I implemented a solution, and did some testing, but it would help if a real case could be used for testing.

**Comment by cportele** [comment]
@jonherrmann can you update the ELF validator, then I will ask the NMCA how raised this to test again and report their results.

**Comment by jonherrmann** [comment]
done.

@thijsbrentjens please update the *.etftp.properties files in the repo:
etf.Author = Thijs Brentjens (Geonovum)
etf.Version = 1.0.2
etf.TestDomain = INSPIRE
etf.LastUpdateDate = 2016-04-14

**Comment by juremekis** [comment]
@cportele, @thijsbrentjens : I am the one who initially reported the problem. I have now tested this fix in the ELF validator and also on the local instance of SoapUI. Unfortunatety I believe the bug is still present when the GetCapabilities document includes an external link to the service metadata.

The bug happens in the "Req 42 (Scenario 1) ExternalServiceMetadata" step. The credentials are not removed but should be. The step is located in the "M-01 - PredefinedWFS" --> "Mandatory INSPIRE GetCapabilities" test case of the "INSPIRE Download Service WFS 2_0_0 ISO19142 TG 3_1" project.

I have not tested the fix on the ATOM project because we don't have any ATOM implementations.

To replay the bug you can use the data from the "SI ELF WFS AU" test object located in the online ETF validator (I don't want to disclose the URLs here on the public forum).

**Comment by jonherrmann** [comment]
@thijsbrentjens this should be changed in the etf-owsgtl, so that the credentials are only used for the host which is set in the serviceEndpoint variable.

@juremekis will post a comment here when the update is ready

**Comment by thijsbrentjens** [comment]
@jonherrmann just to be sure, so the implementation using a Groovy script to remove an Authorization header won't work at all then? We'll need to revert the changes then.

**Comment by jonherrmann** [comment]
@thijsbrentjens i guess, but let me check the ETS first

**Comment by thijsbrentjens** [comment]
Hi @jonherrmann , I reopened this one because I'm not sure if it is resolved now.

**Comment by jonherrmann** [comment]
Not yet. I added the issue to our issue tracker and will fix it until Tuesday.

**Comment by jonherrmann** [comment]
Fixed. Please also check pull request #57

**Comment by juremekis** [comment]
@jonherrmann do you have an estimade date when the new SoapUI plugin will be available? I would like to test this bugfix and need a new version of eft-owsgtl (currently I'm using version 1.3.2).

**Comment by jonherrmann** [comment]
@juremekis you can download the latest public version from here: https://services.interactive-instruments.de/etfdev-af/etf-public-releases/de/interactive-instruments/etf/

@thijsbrentjens please change the etf-owsgtl URL in the README.md to https://services.interactive-instruments.de/etfdev-af/etf-public-releases/de/interactive-instruments/etf/

**Comment by juremekis** [comment]
@jonherrmann I've made a test with the new etf-owsgtl (1.3.7) plugin. The fix is working fine for the "Req 42 (Scenario 1) ExternalServiceMetadata" test step, which was causing trouble. However, when some HTTP requests are called via a groovy script (the "RunMetadataDatasetFromServiceMetadata" test step calls the "GetMetadataDatasetFromServiceMetadata" step one or more times),

``` groovy
testRunner.runTestStepByName("GetMetadataDatasetFromServiceMetadata")
```

the Authorization header doesn't get removed automatically. Please see below for example.

@thijsbrentjens I have trouble with code that removes the authorization header (commit 01a3842; probably 1214071 and 41d61c8 as well), getting "groovy.lang.MissingPropertyException: No such property: key for class: Script1".

I thought I could remove this code with the new version of the etf-owsgtl plugin, but unfortunately can't. Without it the authorization is still included in the HTTP request.

After some research I found out that in my case the "key" and "value" parameters inside the header.each closure:

``` groovy
     header.each
     {
      if (key!="Authorization") {
           newheaders.put(key,val)
      }
     }
```

have to be referenced as "it.key" and "it.value":

``` groovy
     header.each
     {
      if (it.key!="Authorization") {
           newheaders.put(it.key,it.val)
      }
     }
```

Since I've never written Groovy scripts before, I don't know whether this is just a bug or an issue related to Java version or something else. I'm using SoapUI 5.2.1 and JDK 1.8.

**Comment by jonherrmann** [comment]
The Authorization header can't be removed automatically in that context.

Another approach would be to use the [ProjectHelper](http://interactive-instruments.github.io/etf-sui-ae/etf-sui-owsgtl/doc/src/de/interactive_instruments/xtf/ProjectHelper.html) class in that context. In our tests we use the generateStandaloneHttpRequest() method which respects credentials. I will add the mechanism to the runTestStep() method and make this available in v1.3.8.
@thijsbrentjens i will also update one testcase in one test project to show how it can be used.

There are different constructs for defining closures but the first closure can indeed not work as "key" and "val" are note explicitly mapped. Could also be fixed by changing the first line:
`header.each { key, val ->`

**Comment by jonherrmann** [comment]
Authentication credentials are now set in a request if the domain and the _path_ of the _serviceEndpoint_ match the endpoint in the request. This mechanism only works if the owsgtl is used and requires to
- always call Util.updateCredentials( testRunner )  in TestSetup phase
- by using ProjectHelper.runTestStep(...) or ProjectHelper.generateStandaloneHttpRequest(...) for running test steps in scripts
- or by using Util.updateTestStepCredentials( testStep, context )for other tasks where ProjectHelper should not be used

This means that authentication does not work with testRunner.runTestStepByName(), if Util.updateTestStepCredentials() has not been called before.

The tests need to be changed to work with mechanism correctly. I created a pull request pull #60 which changes the "RunMetadataDatasetTest" test step (and minor other changes):

```
import de.interactive_instruments.xtf.*;
SOAPUI_I.init(log,context,testRunner);

ProjectHelper ph = new ProjectHelper();
def capsXmlHolder = ph.getTransferPropertyAsXml("Capabilities")

//Pull out the metadataURLs
def metadataUrlNodes = capsXmlHolder.getNodeValues("//*:MetadataURL/@*:href");
log.info("metadataUrlNodes: " + metadataUrlNodes);

// clear url to test
ph.setTransferProperty("urlToTest","")

// run GetMetadata test for each url
for( url in metadataUrlNodes ) {
   ph.setTransferProperty("urlToTest",url)
  // better to use generateStandaloneHttpRequest() in the future
   ph.runTestStep("GetMetadata")
}
```

I suggest to use it project wide.

One quick note @thijsbrentjens:
If you explicitly declare namespaces and use it with the GroovyUtils getNodeValues() you need to use the namespace prefixes also when you address attributes ( /@xlink:href ).
